# If you find yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: bytedude
author: Marcin S
email: marcin.swieczkowski@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my blog, where I write about programming and my other various interests. Technology is my passion as well as my way of serving the world.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bytedude.com" # the base hostname & protocol for your site, e.g. http://example.com
short_url: "bytedude.com"
twitter_username: 
github_username: "m-cat"
category_dir: category
copyright_year: 2018

repository: "m-cat/bytedude.com"
staticman:
  branch: "master"

# Outputting
permalink: /:title/
timezone: Etc/UTC

# Serving
detach: false

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  # syntax_highlighter_opts:
highlighter: rouge
strict_front_matter: true
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

compress_html:
  blanklines: true
  clippings: all
  comments: all

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
    - Gemfile
    - Gemfile.lock
    - Makefile
    - README.md
    - staticman.yml

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

category_descriptions:
  - {name: "anki", description: ""}
  - {name: "blogging", description: ""}
  - {name: "c", description: ""}
  - {name: "css", description: ""}
  - {name: "emacs", description: ""}
  - {name: "face-offs", description: ""}
  - {name: "health", description: ""}
  - {name: "jekyll", description: ""}
  - {name: "language-learning", description: ""}
  - {name: "org-mode", description: ""}
  - {name: "presentations", description: ""}
  - {name: "productivity", description: ""}
  - {name: "rust", description: ""}
  - {name: "self-improvement", description: ""}
  - {name: "site", description: ""}
  - {name: "web-dev", description: ""}
  - {name: "writing", description: ""}
